### PR TITLE
Setup Github Actions

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Comment by bsipocz** [comment]
Would you think it's better to merge something small first to kick off the CI runs, or shall we get it right from the beginning? (e.g. how much review would you prefer, here?)

**Comment by saimn** [comment]
It's running on my fork so it's fine for now: https://github.com/saimn/pytest-doctestplus/runs/1345403428?check_suite_focus=true

**Comment by saimn** [comment]
Hmm, I don't see why on py36 it runs all the envs, but otherwise it works on the other versions...
https://github.com/saimn/pytest-doctestplus/runs/1345454433?check_suite_focus=true

**Comment by saimn** [comment]
I finally put the matrix in the actions workflow, since for some reason tox-gh-actions was running all envs on Py3.6.
So, it works : https://github.com/saimn/pytest-doctestplus/actions/runs/343608966 (on my fork)
And it is much faster than Travis :tada: 
I also added a build for Python 3.9 + Pytest 6.1

**Review by pllim — APPROVED** [review]
Should merge sooner than later. Can always fix Slack etc as follow-up PRs. I'll approve but let you merge it when you think it is ready.

I also wonder if we should delete the Travis webhook or remove the app, just to be extra safe. 🤔

**Review by astrofrog — APPROVED** [review]
Looks nice!

**Comment by saimn** [comment]
Ok, merging then :)

**Pull request merged**
