### PR TITLE
No error if import fails unconditionally

### PR DESCRIPTION
**Pull request by pllim**
A hacky but more global fix than astropy/astropy#10242 ? 😬

### CODE REVIEW

**Comment by bsipocz** [comment]
I think I've changed my opinion since this morning, and now having this worked around in astropy seems a more right solution, after all collection without optional dependencies should work there, thus this "feature" recovered a few bugs already.

**Comment by pllim** [comment]
As discussed offline, I have no strong feeling either way.

**Comment by astrofrog** [comment]
I think the correct fix is to collect doctests without importing files, instead e.g. parsing files with ast or something similar to find docstrings.

**Comment by pllim** [comment]
How does the `doctest` that ships with `pytest` do it? Will we risk deviating too much from `pytest`?

**Comment by bsipocz** [comment]
pytest's doctest does the exact same we had here for 0.6.0 in #103:

```            try:
                module = self.fspath.pyimport()
            except ImportError:
                if self.config.getvalue("doctest_ignore_import_errors"):
                    pytest.skip("unable to import module %r" % self.fspath)
                else:
                    raise
```

**Comment by pllim** [comment]
Sorry, my question in https://github.com/astropy/pytest-doctestplus/pull/108#issuecomment-622430167 is a reply to https://github.com/astropy/pytest-doctestplus/pull/108#issuecomment-622424855

**Comment by bsipocz** [comment]
oh, I assumed the first one was a question.

**Comment by bsipocz** [comment]
Let's go ahead with this one for now, and maybe #110 for the future. 

I'm merging this now, but they may be some more outstanding issues, as using this with pytest 5.4, there are still asdf related ModuleNotFoundErrors popping up.

**Comment by bsipocz** [comment]
Thank you @pllim!

**Comment by pllim** [comment]
I haven't caught up with all the notifications yet but I am hoping that maybe astropy/astropy#10260 will handle it. If not, perhaps the last resort is to have `setup.cfg` ignore it on the `astropy` side. 🤞

**Pull request merged**
