### PR TITLE
add REMOVE_TRAILING_WHITESPACE flag

### LINKED ISSUE #70: add flag for removing trailing spaces on each line but keep inner spaces
Useful for comparing multiline strings:

```
>>> print(
...   "foo   "
...   "   bar"
... )
foo
  bar
```
Most IDEs will remove trailing spaces after `foo`. Also it can tedious to add spaces to each line in the expected input string (I already know this pain).

### PR DESCRIPTION
**Pull request by vanyakosmos**
close #70

### CODE REVIEW

**Comment by vanyakosmos** [comment]
Yeah, better to use `IGNORE_TRAILING_WHITESPACE` for naming consistency.

**Comment by astrofrog** [comment]
@vanyakosmos - thanks! If possible, would you be able to rebase this pull request to get rid of the merge commit? (no problem if not though)

**Comment by vanyakosmos** [comment]
I'm not sure how to do this correctly. Usually I rebase in interactive mode and squash unnecessary commits, but with "merge commit" things are getting complicated, because now `git rebase -i HEAD~2` will unpack second (merge) commit into list of commits from that merge. And I can't remove any of those commits.

`git rebase -i HEAD~2`:
Screen Shot 2019-11-04 at 14 53 45

Any suggestions?

**Comment by astrofrog** [comment]
@vanyakosmos - try rebasing on the latest commit in master, e.g.

```
git rebase -i e9e8adf3
```

any luck?

**Comment by vanyakosmos** [comment]
On second thought this feature is probably overkill. 

I can check correct formatting in the regular test. And in the doctest I just need to verify that function produce at least somewhat similar result. `NORMALIZE_WHITESPACE` already does the trick.

**Pull request closed without merging**
