### PR TITLE
Doctests in ufuncs should respect __doctest_skip__

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Review by mhvk — APPROVED** [review]
Looks good to me! Definitely makes sense to pass it through the same selection criteria

**Comment by pllim** [comment]
I think we should document how to use `__doctest_skip__` to skip unwanted ufunc doctest?

**Comment by lpsinger** [comment]
Following recent discussions, I have added back the `--doctest-ufunc` option, which is disabled by default.

**Comment by pllim** [comment]
Re-running astropy/astropy#12853 🤞

**Comment by pllim** [comment]
So.... do we *not* want to use it over at `astropy` then? If we do, how do we do it without astropy/astropy#12861 ?

**Comment by lpsinger** [comment]
> So.... do we _not_ want to use it over at `astropy` then? If we do, how do we do it without [astropy/astropy#12861](https://github.com/astropy/astropy/pull/12861) ?

You could revert [#12861](https://github.com/astropy/astropy/pull/12861) if you wanted.

**Comment by pllim** [comment]
@mhvk , do you really want ufunc doctesting in astropy ?

**Comment by mhvk** [comment]
We don't have that many ufuncs, and I don't think any have examples that would be tested, since they are really for internal use. So, certainly no hurry. On the other hand, long-term we might as well test things in case things change.

**Review by pllim — APPROVED** [review]
`astropy` core seems fine with this patch. Thanks!

Shall we merge?

**Review by nstarman — APPROVED** [review]

**Comment by pllim** [comment]
Thanks!

**Comment by lpsinger** [comment]
Thank you! When do you expect to do the next release of pytest-doctestplus?

**Comment by pllim** [comment]
@lpsinger , #177 is blocking the release.

**Comment by pllim** [comment]
I'll push a release soon. Stay tuned!

**Comment by pllim** [comment]
v0.12.0 is released on PyPI.

**Pull request merged**
