### PR TITLE
ENH: Support testcleanup

### LINKED ISSUE #164: Why is there testsetup but no testcleanup?
https://github.com/astropy/pytest-doctestplus/blob/16d6d4527439516d5a370b34941e4f1f549268f5/pytest_doctestplus/sphinx/doctestplus.py#L54

There appears to be no support for `testcleanup` directive even though this package is supposed to expand on the existing `doctest` module from upstream. As a result: https://github.com/astropy/astropy/pull/12150#issuecomment-918575446

### PR DESCRIPTION
**Pull request by pllim**
Fix #164

### CODE REVIEW

**Comment by saimn** [comment]
Looks good to me but maybe another pair of eyes would be useful.

**Review by saimn — APPROVED** [review]

**Comment by Cadair** [comment]
Looks reasonable, but I don't really know how this works.

**Comment by pllim** [comment]
YOLO?

**Comment by nstarman** [comment]
This looks very useful! I've been using

```
.. doctest::
   :hide:

   >>> code
```￼

But this PR is cleaner. And better explains why the code is hidden.

**Comment by saimn** [comment]
Ok, let's merge then! Thanks @pllim.

**Comment by pllim** [comment]
@saimn , should the next release be v0.10.2 or v0.11.0 ?

**Pull request merged**
