### PR TITLE
Add comment characters for Markdown

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! But what is the motivation for this patch and can you please add a test?

**Comment by lpsinger** [comment]
The motivation is that I have doctests in my Markdown README file in https://github.com/skyportal/healpix-alchemy, and I am tired of the warning, `file format '.md' is not recognized, assuming '\.\.' as the comment character`.

**Comment by lpsinger** [comment]
I added some tests.

**Review by saimn — APPROVED** [review]
Looks good, thanks @lpsinger.

**Pull request merged**
