### PR TITLE
Setup updates, remove Python 3.6

### PR DESCRIPTION
**Pull request by saimn**
Small updates while using doctestplus as an example for sphinx-astropy.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Please add a changelog entry as we used to note dropping of supported versions. Otherwise this is good to go.

**Review by pllim — COMMENTED** [review]
What does the build wheel label for?

**Review by pllim — APPROVED** [review]
Ah, I get it now. LGTM and I agree with @bsipocz 's comment about change log.

**Comment by saimn** [comment]
Ok, done.

**Pull request merged**
