### PR TITLE
Revert "Use windows-2019 for GitHub Actions jobs"

### PR DESCRIPTION
**Pull request by lpsinger**
Reverts astropy/pytest-doctestplus#178.

This might be fixed now...

### CODE REVIEW

**Comment by pllim** [comment]
Doesn't appear so.

**Comment by lpsinger** [comment]
@pllim, would you please retry the CI jobs? https://github.com/actions/virtual-environments/issues/5141#issuecomment-1095289596 reports that the windows-latest issue may be fixed now.

**Comment by pllim** [comment]
Let me close/re-open and see.

**Comment by pllim** [comment]
Yay. Thanks!

**Pull request merged**
